"""
Pydantic models for the ATS engine — both the INPUT (a candidate's structured
Master Resume) and the OUTPUT (the LLM's scored, tailored result).

WHY A STRUCTURED "MASTER RESUME" INSTEAD OF RAW RESUME TEXT?
    Feeding an LLM a plain-text resume and asking it to "tailor it" invites
    two problems: (1) the model can silently invent a new bullet, employer,
    or metric that sounds plausible but is fabricated, and (2) there's no
    stable identifier to check its output against afterward. Giving every
    bullet a `bullet_id` up front turns "did the LLM hallucinate?" from a
    fuzzy judgment call into a mechanical set-membership check — see
    `validate_no_hallucination()` at the bottom of this file, used by
    `eagent.ats.llm.analyze_and_tailor()`.

WHY TWO SEPARATE MODEL FAMILIES IN ONE FILE?
    `MasterResume*` describes ground truth (what's true about the candidate).
    `ATSAnalysisResult` / `TailoredResume` describe the LLM's *claims* about
    how to present that truth for one specific job. Keeping them as distinct
    types (rather than one big mutable resume object) makes the "the output
    must only reference the input" contract explicit and checkable.
"""
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, EmailStr, Field, HttpUrl, field_validator


def _dedupe_lowercase(value: List[str]) -> List[str]:
    """Normalize a keyword/skill list: trim, lowercase, drop dupes, preserve order.

    Same instinct as JobPosting.tech_stack in Phase 2 (src/eagent/models.py) —
    keyword lists get compared and joined downstream (matched vs. missing,
    prioritized vs. master-resume skills), so case/whitespace inconsistency
    from the LLM would silently break those comparisons.
    """
    seen: List[str] = []
    for item in value:
        norm = item.strip().lower()
        if norm and norm not in seen:
            seen.append(norm)
    return seen


# =============================================================================
# INPUT: the candidate's Master Resume (ground truth, never generated by an LLM)
# =============================================================================


class MasterResumeBullet(BaseModel):
    """One real, human-written accomplishment bullet from the candidate's history."""

    bullet_id: str = Field(..., description="Stable id, e.g. 'acme-2022-01'. Never regenerate ids.")
    text: str = Field(..., min_length=1)


class MasterResumeExperience(BaseModel):
    """One job in the candidate's real work history."""

    company: str
    title: str
    start_date: str = Field(..., description="e.g. '2022-01' — free-form but consistent")
    end_date: Optional[str] = Field(default=None, description="None means 'Present'")
    bullets: List[MasterResumeBullet] = Field(default_factory=list)


class MasterResume(BaseModel):
    """The single source of truth the ATS engine is allowed to draw from.

    This is authored by the candidate (you), stored as JSON, and never
    written to by the LLM. See data/master_resume.example.json for a sample.
    """

    full_name: str
    email: EmailStr
    phone: Optional[str] = None
    location: Optional[str] = None
    linkedin_url: Optional[HttpUrl] = None

    summary: str = Field(..., description="Candidate's own general-purpose summary (untailored).")
    skills: List[str] = Field(default_factory=list)
    experience: List[MasterResumeExperience] = Field(default_factory=list)

    def bullet_ids(self) -> set:
        """All valid bullet_ids across every job — the whitelist for hallucination checks."""
        return {b.bullet_id for exp in self.experience for b in exp.bullets}

    def bullet_by_id(self, bullet_id: str) -> Optional[MasterResumeBullet]:
        for exp in self.experience:
            for b in exp.bullets:
                if b.bullet_id == bullet_id:
                    return b
        return None


# =============================================================================
# OUTPUT: what the LLM returns (requirement #1)
# =============================================================================


class TailoredBullet(BaseModel):
    """One bullet selected (and lightly reworded) from the Master Resume.

    `bullet_id` MUST reference a real MasterResumeBullet — the LLM is not
    asked to invent facts, only to select, reorder, and rephrase existing
    ones. `validate_no_hallucination()` enforces this after the fact.
    """

    bullet_id: str
    tailored_text: str = Field(..., min_length=1)


class TailoredResume(BaseModel):
    """The tailored presentation layer for one specific job application."""

    summary: str = Field(..., min_length=1, description="Rewritten summary targeting this JD.")
    prioritized_skills: List[str] = Field(
        default_factory=list, description="Subset/reordering of the candidate's real skills."
    )
    bullet_points: List[TailoredBullet] = Field(
        default_factory=list, description="Selected + re-ranked bullets, most relevant first."
    )

    @field_validator("prioritized_skills", mode="before")
    @classmethod
    def _normalize_prioritized_skills(cls, value: List[str]) -> List[str]:
        return _dedupe_lowercase(value or [])


class ATSAnalysisResult(BaseModel):
    """The full, validated shape of one LLM call's output. See requirement #1."""

    ats_score: float = Field(..., ge=0, le=100, description="0-100 match between resume and JD.")
    matched_keywords: List[str] = Field(default_factory=list)
    missing_hard_skills: List[str] = Field(default_factory=list)
    tailored_resume: TailoredResume

    @field_validator("matched_keywords", "missing_hard_skills", mode="before")
    @classmethod
    def _normalize_keyword_lists(cls, value: List[str]) -> List[str]:
        return _dedupe_lowercase(value or [])


class HallucinationError(ValueError):
    """Raised when the LLM's output references facts not present in the Master Resume."""


def validate_no_hallucination(result: ATSAnalysisResult, master_resume: MasterResume) -> None:
    """The programmatic anti-hallucination / anti-fabrication guard.

    "Re-ranked bullet points" (requirement #1) means every bullet from the
    Master Resume must appear exactly once, just reordered and reworded —
    not a hallucinated new one, and not a silently dropped real one. That
    turns "did the model behave" into three mechanical set/multiset checks
    against the Master Resume — no LLM judge, no fuzzy matching, fast and
    fully deterministic:

      1. No unknown bullet_id — the model can't invent a bullet or mangle an id.
      2. No missing bullet_id — the model can't silently omit a real one.
      3. No duplicate bullet_id — the model can't repeat one to pad the resume.

    Plus one more:
      4. Every prioritized skill must be a real skill of the candidate's. The
         model may choose *which* real skills to foreground for this job,
         never claim one the candidate doesn't have.

    Raises:
        HallucinationError: with every violation listed (not just the first),
            so a retry prompt (see eagent.ats.llm) can show the model
            everything it needs to fix at once.
    """
    violations: List[str] = []

    known_bullet_ids = master_resume.bullet_ids()
    returned_ids = [tb.bullet_id for tb in result.tailored_resume.bullet_points]
    returned_id_set = set(returned_ids)

    unknown = returned_id_set - known_bullet_ids
    if unknown:
        violations.append(f"unknown bullet_id(s), not in the Master Resume: {sorted(unknown)}")

    missing = known_bullet_ids - returned_id_set
    if missing:
        violations.append(
            f"missing bullet_id(s) — re-ranking must include every original bullet exactly "
            f"once, these were dropped: {sorted(missing)}"
        )

    if len(returned_ids) != len(returned_id_set):
        dupes = sorted({b for b in returned_ids if returned_ids.count(b) > 1})
        violations.append(f"duplicate bullet_id(s): {dupes}")

    known_skills = {s.strip().lower() for s in master_resume.skills}
    for skill in result.tailored_resume.prioritized_skills:
        if skill.lower() not in known_skills:
            violations.append(f"prioritized_skills contains '{skill}', which is not one of the candidate's real skills")

    if violations:
        raise HallucinationError("; ".join(violations))
